# Window rules
windowrulev2 = suppressevent maximize, class:.*

# Layer rules
layerrule = noanim, rofi

decoration {
    blur {
        enabled = true
        size = 10
        passes = 1
        new_optimizations = true
    }
}

windowrulev2 = opacity 0.9, class:^(kitty)$
windowrulev2 = opacity 0.8, class:^(Rofi)$
