# Import theme colors
source = ~/.config/hypr/mocha.conf

# Import modular configurations
source = ~/.config/hypr/keybinds.conf
# source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/startup.conf
source = ~/.config/hypr/rules.conf

# Main Applications
$terminal = kitty
$fileManager = nautilus
$menu = rofi -show drun -modi drun,filebrowser,run,window

# Xwayland configuration
xwayland {
    force_zero_scaling = true
}

# Environment variables
env = XCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME,qt6ct

# Input configuration
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =
    kb_options = ctrl:nocaps
    follow_mouse = 1
    touchpad {
        natural_scroll = yes
    }
    sensitivity = 0
}

# General appearance
general {
    border_size = 3
    col.active_border = $mauve $flamingo 90deg
    col.inactive_border = $subtext0
    resize_on_border = true
    gaps_in = 6
    gaps_out = 10
    layout = dwindle
    allow_tearing = false
}

# Window decorations
decoration {
    rounding = 4
    blur {
        enabled = true
        size = 10
        passes = 1
    }
}

# Animations
animations {
    enabled = true
    bezier = linear, 0.0, 0.0, 1, 1
    animation = borderangle, 1, 50, linear, loop
    animation = workspaces, 1, 0.5, default
    animation = windows, 0, 0.1, default
    animation = fade, 0, 0.1, default
}

# Layout configuration
dwindle {
    pseudotile = yes
    preserve_split = yes
}

# Gestures
gestures {
    workspace_swipe = off
}

# Misc settings
misc {
    force_default_wallpaper = 0
}

# Device-specific settings
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
