# Window rules
windowrule {
    name = suppress-maximize
    match:class = .*
    suppress_event = maximize
}

# Layer rules
layerrule = blur off rofi

windowrule {
    name = kitty-opacity
    match:class = ^(kitty)$
    opacity = 0.9
}

windowrule {
    name = rofi-opacity
    match:class = ^(rofi)$
    opacity = 0.8
}

windowrule {
    name = pangp-ui
    match:class = ^(PanGPUI)$
    no_initial_focus = on
    move = 1829 40
}

# Claude Launcher
windowrule {
    name = claudeai-float
    match:class = ^(chrome-claude\.ai__new-Profile_1)$
    float = on
}
windowrule {
    name = claudeai-size
    match:class = ^(chrome-claude\.ai__new-Profile_1)$
    size = 1200 800
}
windowrule {
    name = claudeai-center
    match:class = ^(chrome-claude\.ai__new-Profile_1)$
    center = on
}
