plugins:
  gonzo:
    shortCut: Shift-G
    description: "Gonzo logs"
    scopes:
      - po
    command: sh
    background: false
    confirm: false
    args:
      - -c
      - "kubectl logs -f $NAME -n $NAMESPACE --context $CONTEXT --all-containers | (gonzo; kill 0)"

  gonzo-popup:
    shortCut: Ctrl-G
    description: "Gonzo Popup"
    scopes:
      - po
    command: sh
    background: false
    confirm: false
    args:
      - -c
      - "trap 'kill 0' EXIT; kubectl logs -f --timestamps $NAME -n $NAMESPACE --context $CONTEXT --all-containers | gonzo"
